title: ▪️▫️ Felicia Ann Kelley ▪️▫️
description: A bold typographic theme inspired by Swiss design.
social_link: Twitter/fkelley046
social_username: fkelley046
github_repo: faykeltay
github_username: 'faykeltay '
theme_color: Cyan
remote_theme: CodeIsPoetry
baseurl: /fak
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
